-- SQL Script for creating the products table in Supabase
-- Esegui questo script nell'SQL Editor di Supabase per configurare il database.

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  squadra TEXT NOT NULL,
  categoria TEXT NOT NULL,
  versione TEXT NOT NULL,
  stagione TEXT NOT NULL,
  prezzo NUMERIC DEFAULT 23.99,
  immagine TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- (Opzionale) Se desideri abilitare Row Level Security (RLS) ma consentire la lettura pubblica:
-- ALTER TABLE products ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Consenti lettura pubblica" ON products FOR SELECT USING (true);
-- CREATE POLICY "Consenti inserimento pubblico" ON products FOR INSERT WITH CHECK (true);
-- CREATE POLICY "Consenti modifica pubblica" ON products FOR UPDATE USING (true);
-- CREATE POLICY "Consenti eliminazione pubblica" ON products FOR DELETE USING (true);
